name: OPT1.3B
cfg_path: ckpts/opt1.3b
truncation_side: right
max_context_len: 256
max_out_len: 256
lora:
  flag: True
  rank: 16
  alpha: 16
  target_modules: [q_proj, k_proj, v_proj, out_proj]
  dropout: 0.0
